notes for chapter17
r4ds/bookclub-tmwr pull request #105
Opened 2021-09-20 11:12 UTC by Fgazzelloni

2021-09-21 12:14 UTC, jonthegeek requested changes
A few things:
* We're trying to co-create a single set of notes that can be reused by future clubs. Can you merge the notes into the existing file for the corresponding chapters? If not, please put them in the `other` folder to be sorted out by later groups.
* The build failed. The code chunk where you create `bean_res` has `eval = FALSE`, but then you reference `bean_res` later. You need to define it in an evaluated chunk if you want to use it.
* Please name your `{r}` code chunks. That makes it *much* easier to debug (and someone in a future cohort might be doing the debugging, so they might not have any idea where to start). The names have to be unique (throughout the whole book), so something like `17-define-beans-res` is better than simply `define-variables`, for example.

Thanks for actively participating!

2021-09-23 14:22 UTC, Fgazzelloni commented
Hello Jon,
hope now is fine. I have deleted the previous commit files, and directly proposed few major additions to 17-dimensionality_reduction.Rmd .
You can delete this pull request (I don't know how to do it) and check if you can see the changes I have made directly from github into 17-dimensionality_reduction.Rmd .

2021-09-23 14:50 UTC, jonthegeek commented
We don't have to delete this PR, I'll review the latest changes you made as part of this PR and hopefully be able to accept soon! There's at least one edit left because the book still didn't build properly, but that will PROBABLY be more straightforward.

Thanks for understanding! We're going to make something great together!

I'll review this... maybe later today, but more likely it'll have to wait 'til Saturday.

2021-09-23 20:45 UTC, jonthegeek commented
This is the error that is currently preventing the book from building:
```
Error in knitr::include_graphics(here::here("images/17-workflow.png")) : 
  Cannot find the file(s): "/Users/runner/work/bookclub-tmwr/bookclub-tmwr/images/17-workflow.png"
```

2021-09-26 16:38 UTC, jonthegeek requested changes
Need to update references to some images. I'll accept these if possible to see if that fixes the build.

2021-09-26 16:38 UTC, jonthegeek commented on 17-dimensionality_reduction.Rmd
> +knitr::include_graphics(here::here('images/pls.png'))
```suggestion
knitr::include_graphics("images/pls.png")
```
In this context, it looks like `here::here` just confuses things. The relative path should do it. I'm going to try to accept these changes if I can so we can hopefully make this work.

2021-09-26 16:38 UTC, jonthegeek commented on 17-dimensionality_reduction.Rmd
> +knitr::include_graphics(here::here('images/pls_algo.png'))
```suggestion
knitr::include_graphics("images/pls_algo.png")
```

2021-09-26 16:38 UTC, jonthegeek commented on 17-dimensionality_reduction.Rmd
> +knitr::include_graphics(here::here('images/17-workflow.png'))
```suggestion
knitr::include_graphics("images/17-workflow.png")
```

2021-09-26 16:49 UTC, jonthegeek requested changes
Ok, `here::here` wasn't the issue (thankfully). This file appears to be missing, please add it or remove the reference:

```Error in knitr::include_graphics("images/17-workflow.png") : 
  Cannot find the file(s): "images/17-workflow.png"
```

That said I haven't actually reviewed the changes yet, I'm just trying to get it to work so I can review it in context.

2021-09-26 22:48 UTC, jonthegeek requested changes
Please remove the doMC requirement and calls. That package isn't available for Windows, which makes this uneditable on a Windows machine. If we actually need it to compile the book, then we've definitely done something wrong.

One way to get around this issue is to make any code blocks that really need it `eval = FALSE`, and then show their output from RDS. But it really shouldn't be necessary to use this package in the notes of the club, because that makes the club inaccessible to Windows users.

Also please add titles for all `{r} blocks in the code. It makes debugging much easier.

2021-11-23 15:51 UTC, jonthegeek requested changes
I'd like to get this merged in. Do you think you can make these changes and get it working?

2021-11-23 15:51 UTC, jonthegeek commented on 17-dimensionality_reduction.Rmd
> +    bean_res <- readRDS(file = "data/bean_res.rda")
```suggestion
    bean_res <- readRDS(file = "data/bean_res.RDS")
```

2021-11-23 15:51 UTC, jonthegeek commented on 17-dimensionality_reduction.Rmd
> +We do not actually read this back in these notes as the `.rda` file is too big for loading it, but you can use these commands on your machine:
```suggestion
We do not actually read this back in these notes as the `.rds` file is too big for loading it, but you can use these commands on your machine:
```

2021-11-23 15:51 UTC, jonthegeek commented on DESCRIPTION
> +    doMC,
Please remove the doMC Import. If this package is used in your notes, turn off evaluation of those parts. doMC does not work on Windows, and the bookclubs are meant to be usable on all machines.

2022-01-08 19:40 UTC, jonthegeek commented
I'm going to go ahead and close this PR. When you get to this chapter with Cohort 4, we can sort out any relevant changes!

2022-01-08 19:40 UTC, closed without merging